### ISSUE TITLE
Add field owner to Links

### ISSUE THREAD

**Issue by Moses-odessa** [JujaLabs/juja-platform#52]
User story: 
> Я как пользователь хочу закреплять добавленные мной ссылки за моим пользователем, для того чтобы потом легко найти 

0) changes/additions proposed with this issue and what they are provided for
	* we need a field to identify the user making request for a link edition/removal with archiving
	* the best way is to add an appropriate field to the model
	* the name of such a field could be 'owner'
	
1) objects changing or adding to the project
	* add a String field to Link model
	* add a String field to SaveLinkRequest model
	
2) API annotations provided with changes/additions required
```
	@ApiModel 
	public class Link 
	
	@ApiModelProperty(value = "A person who saves this link, used to identify while changing/archiving", required = true)
	public String getOwner()	
```
	
3) Process (or may be USAGE???) description, examples
	To be sure if the person, who makes request, has the rights to change/archive the link, we need their user id to be compared with id of a person, who has created this link before. 

4) requirements and limitations 
	* The field has to be non-null
	* This model property is required 
	* Tests written for Link and SaveLinkRequest should include provided field

**Comment by Benkoff** [comment]
#52

User story: 
> Я как пользователь хочу закреплять добавленные мной ссылки за моим пользователем, для того чтобы потом легко найти 

0) changes/additions proposed with this issue and what they are provided for
	* we need a field to identify the user making request for a link edition/removal with archiving
	* the best way is to add an appropriate field to the model
	* the name of such a field could be 'owner'
	
1) objects changing or adding to the project
	* add a String field to Link model
	* add a String field to SaveLinkRequest model
	
2) API annotations provided with changes/additions required
```
	@ApiModel 
	public class Link 
	
	@ApiModelProperty(value = "A person who saves this link, used to identify while changing/archiving", required = true)
	public String getOwner()	
```
	
3) Process (or may be USAGE???) description, examples
	To be sure if the person, who makes request, has the rights to change/archive the link, we need their user id to be compared with id of a person, who has created this link before. 

4) requirements and limitations 
	* The field has to be non-null
	* This model property is required 
	* Tests written for Link and SaveLinkRequest should include provided field
