### ISSUE TITLE
Agenda 26.12.2017

### ISSUE THREAD

**Issue by adaleorion** [JujaLabs/juja-platform#61]
1.  Как у кого дела ? Текущее состояние.
2.  Как будем поступать с доками, сейчас много правок (@ivshapovalov )
3.  Как у slack забрать все данные :)
     как слак удаляет сообщения,
     как слак смотрит кол-во сообщений перед удалением, он проверяет  в общем по команде или по каждому каналу и как принимается решение что удалить, а  что оставить,
    от этого знания будет понятно что делать с частотой
\*

**Comment by ivshapovalov** [comment]
4. Использование Feign на каком уровне и почему

**Comment by val-fed** [comment]
5. Нюанс с сохранением отредактированных сообщений. 
В случае реал-тайм сохраняется только оригинальное сообщение, после редактирования повторно не отсылается.

**Comment by ivshapovalov** [comment]
Вообще ничего не происходит? Может какое то другое сообщение

**Comment by adaleorion** [comment]
open api - https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md

**Comment by adaleorion** [comment]
Блин есть такое будет происходить, то мы потеряем историю изменений, надо думать над более хитрой схемой логирования
