### ISSUE TITLE
Fix dependencies issue for swagger and springfox

### ISSUE THREAD

**Issue by adaleorion** [JujaLabs/juja-platform#76]
'swagger-annotations', version: '2.0.0-rc2' is a release candidate issued to support OpenAPI 3.0’s main features, some features are missing and will be added in the final release. since there is no final release yet, we use version 1.5 and springfox-swagger 2 (not OpenAPI 3.0). i'm not sure if we get any problems with version 2.0.0-rc2 but they can happen so i'd be grateful if you'd get rid of compile group: 'io.swagger', name: 'swagger-annotations', version: '2.0.0-rc2' and update 'io.springfox:springfox-swagger2:2.6.1' to the latest version, namely https://mvnrepository.com/artifact/io.springfox/springfox-swagger2/2.8.0 like others do. thanks!

**Comment by Benkoff** [comment]
join #50 
Fixed there
